backend:
  name: git-gateway
  branch: main   # or 'master' or whichever branch you deploy from

media_folder: "public/images/uploads"   # Where uploaded images go in your repo
public_folder: "/images/uploads"        # The URL path used by the site

collections:
  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"         # filename
    extension: "md"
    format: "frontmatter"    # use YAML frontmatter
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Category", name: "category", widget: "select", options: ["illustration", "board-game", "ux-ui"] }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
